require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/api/v1/vets', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Vet. As you add validations to Vet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for(:vet) }

  let(:invalid_attributes) { { name: '', age: 2040, graduation_date: '' } }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::VetsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Vet.create! valid_attributes
      get api_v1_vets_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      vet = Vet.create! valid_attributes
      get api_v1_vet_url(vet), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Vet' do
        expect do
          post api_v1_vets_url,
               params: { vet: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Vet, :count).by(1)
      end

      it 'renders a JSON response with the new vet' do
        post api_v1_vets_url,
             params: { vet: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Vet' do
        expect do
          post api_v1_vets_url,
               params: { vet: invalid_attributes }, as: :json
        end.to change(Vet, :count).by(0)
      end

      it 'renders a JSON response with errors for the new vet' do
        post api_v1_vets_url,
             params: { vet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        { name: 'a_new_name', age: 20 }
      end

      it 'updates the requested vet' do
        vet = Vet.create! valid_attributes
        patch api_v1_vet_url(vet),
              params: { vet: new_attributes }, headers: valid_headers, as: :json
        vet.reload
        new_attributes.each_pair do |key, value|
          expect(vet[key]).to eq(value)
        end
      end

      it 'renders a JSON response with the vet' do
        vet = Vet.create! valid_attributes
        patch api_v1_vet_url(vet),
              params: { vet: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the vet' do
        vet = Vet.create! valid_attributes
        patch api_v1_vet_url(vet),
              params: { vet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested vet' do
      vet = Vet.create! valid_attributes
      expect do
        delete api_v1_vet_url(vet), headers: valid_headers, as: :json
      end.to change(Vet, :count).by(-1)
    end
  end
end
